### ISSUE TITLE
Regarding WireGuard LXC

### ISSUE THREAD

**Issue by donaldzou** [community-scripts/ProxmoxVE#245]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Hi @MickLesk,

My name is Donald Zou, and I'm the creator of [WGDashboard](https://github.com/donaldzou/WGDashboard).

Recently, it came to our attention that our project is being used in `wireguard-install.sh`, and we're happy that it has been chosen and adopted by the ProxmoxVE community!

We were wondering if it would be possible to add more guidance on https://community-scripts.github.io/ProxmoxVE/scripts?id=wireguard, as some users are mixing up WGDashboard and WireGuard and mistakenly thinking they’re the same. Additionally, it might be helpful to include a WireGuard configuration template within the guide or the installation script to simplify things for users.

Looking forward to hearing back from you.

Best,  
Donald

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

**Comment by MickLesk** [comment]
Hi Donald,

I understand what you mean, but I'm not sure what else to add to the website?
A note that WGDashboard is a management interface for existing configurations? 

Feel free to give us suggestions. We can also open a “Discussion”, “Announcement” at any time by defining further steps. 

Example: 
https://github.com/community-scripts/ProxmoxVE/discussions/193
or
https://github.com/community-scripts/ProxmoxVE/discussions/192

later there will probably be real wiki entries, but unfortunately we are not yet ready at the current stage of the project, which is why we note all this in Discussions.

**Comment by MickLesk** [comment]
@donaldzou 

If you like, feel free to link our project as well. :-) This way, Proxmox users can see it too.

**Comment by donaldzou** [comment]
> @donaldzou
> 
> If you like, feel free to link our project as well. :-) This way, Proxmox users can see it too.

@MickLesk 

Hi yes! The doc just updated with linking to community-script!

[🛠 Install](https://donaldzou.github.io/WGDashboard-Documentation/install.html#for-proxmox-virtual-environment)
[📝 Requirements](https://donaldzou.github.io/WGDashboard-Documentation/requirements.html)
