### ISSUE TITLE
Wallos: /var/log/cron does not exist

### ISSUE THREAD

**Issue by burgerga** [community-scripts/ProxmoxVE#315]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

`/var/mail/root` is full with emails like:

```bash
Subject: Cron <root@wallos> php /opt/wallos/endpoints/cronjobs/sendverificationemails.php >> /var/log/cron/sendverificationemail.log 2>&1
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
Message-Id: <20241117190601.8D49820965@wallos.localdomain>
Date: Sun, 17 Nov 2024 19:06:01 +0000 (UTC)

/bin/sh: 1: cannot create /var/log/cron/sendverificationemail.log: Directory nonexistent
```

caused by https://github.com/community-scripts/ProxmoxVE/blob/61d2e0d599b88a3273198c6b747285049636b926/install/wallos-install.sh#L61-L72

I think you could redirect the output to `logger`, which also avoids filling up the disk (see https://serverfault.com/a/434902/178440)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by burgerga** [comment]
I see this was in the official instructions, so I opened an issue at wallos as well

**Comment by MickLesk** [comment]
I fix it tomorrow with the other Wallos issue

**Comment by MickLesk** [comment]
Update is enough. If there is no Update available Just enter:   mkdir -p /var/log/cron

**Comment by havardthom** [comment]
@MickLesk

**Comment by MickLesk** [comment]
Works fine for me. Why do you dont have an .db File? Is that a clean install without any user activity? Never registrated? 

Ive build a little check, if the file is available for next pr. But it's still strange. It's there for me.

**Comment by havardthom** [comment]
We move what needs to be migrated out of the old app, remove the old app, get the new app, move migrated data into the new app. We don't want to copy files into the old app because that could mix old files with new files.
Anyway, if you now have `/opt/wallos/db/wallos.db` then the update should work for you **after** https://github.com/community-scripts/ProxmoxVE/pull/339 is merged. The problem in [your post](https://github.com/community-scripts/ProxmoxVE/issues/315#issuecomment-2483634383) was that the images backup command failed, and that was after your database was moved, so when you tried to run the update again it could not find the database anymore
