### ISSUE TITLE
Missing misc/bluetooth.sh

### ISSUE THREAD

**Issue by SunnyM-ha** [community-scripts/ProxmoxVE#323]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Using the Home Assistant Core LXC script, bluetooth does not work inside the container.
tteck made a fix for this here : https://github.com/tteck/Proxmox/discussions/719
However the https://github.com/tteck/Proxmox/raw/main/misc/bluetooth.sh script he created for this no longer seems to exist. Do you guys still have access to his repo and could restore this file?

(Or has anyone else found an alternate fix for bluetooth missing from HA-Core LXC? I recreated as Priviledged too but no luck, have spent literally 3-4 hours playing around with linux settings to no avail)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

### Please provide detailed steps to reproduce the issue.

Install HomeAssistant Core LXC using the script, run "systemctl status bluetooth" and errors on a fresh install

**Comment by newzealandpaul** [comment]
**WARNING: I DO NOT THINK YOU SHOULD RUN THIS SCRIPT**

Ok, the warning is out of the way, here is the script you are looking for.

https://raw.githubusercontent.com/tteck/Proxmox/f22df25bd2eaecfa9f587452ff60fda1ae6c94cd/misc/bluetooth.sh

Note: tteck removed it in 2022 and didn't give a reason. I presume it was removed because it no longer worked. The script sets up some backport repos and then does the following:

```
systemctl enable dbus-broker.service
```

and

```
apt-get -t bullseye-backports install -y bluez*
```

My advice is NOT to run this script. 

I do advise you to use the script for the Home Assistant HAOS VM. It makes life so much easier. Then use USB passthrough to share your bluetooth device to the VM.

**Comment by SunnyM-ha** [comment]
Thanks for that, looking through the script and digging into the details it does seem outdated as 2 of those 3 things are already the default now, so I don't think it will help - I won't run it.

I actually already have HA OS running as a VM, however I've slowly switched everything away from docker to LXC and each container is using 0.8% to 7% of my total system RAM. That one HAOS VM is using 48% on its own, so I was trying to get that last one converted to LXC. I have it setup and its using 6% of RAM, so much MUCH smaller, but if I cant get USB passthrough working then I'll have to delete it and go back to the VM.

Thanks for looking this up :)
