### ISSUE TITLE
Kimai

### ISSUE THREAD

**Issue by MickLesk** [community-scripts/ProxmoxVE#387]
https://github.com/community-scripts/ProxmoxVE/discussions/107

Application Name
Kimai OpenSource Timerecording

Website
https://www.kimai.org/de/

Description
Kimai is an open-source time-tracking software designed for freelancers, small teams, and businesses to efficiently track, manage, and analyze work hours. This web-based tool enables users to log their work time with ease, associating entries with specific clients, projects, and tasks.

**Comment by michaelh99** [comment]
Running into this when running the script on proxmox 8.3.1

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/kimai.sh)"

 ⠇400 too many argumentsr 
pct create <vmid> <ostemplate> [OPTIONS]
bash: line 201: exit: A problem occured while trying to create container.: numeric argument required

Before opening a PR I thought I'd see if this is an otherwise known issue
