### ISSUE TITLE
Big-bang bang update (#333) broke most of my LXC updates

### ISSUE THREAD

**Issue by dsiebel** [community-scripts/ProxmoxVE#404]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

In #333 the resource checks were changed in a way that now breaks almost all my LXC updates, e.g.:

```
⚠️  Required: 1 CPU, 1024MB RAM | Current: 1 CPU, 512MB RAM
Please ensure that the Uptime Kuma LXC is configured with at least 1 vCPU and 1024 MB RAM for the build process.
```

I fine-tuned the resources of my LXC containers to what they actually need, the new resource checks however would require me to:

1. switch back to default resource values (might not be available on the PVE node)
2. reboot the container (downtime)
3. run the update
4. switch back to chosen values (downtime, again)

Am I holding this wrong? Is there a better way to do the updates?

This only happened after running `sed -i 's/tteck\/Proxmox/community-scripts\/ProxmoxVE/g' /usr/bin/update` to switch to the new repo (😢).
The old update scripts, still work fine, but will be outdated soon enough.

To be honest, I think the previous approach of briefly over-provisioning the container, 
in case of resource intensive build processes, was perfectly fine.
Especially considering the resources were reverted, after install or update, to the chosen/previous values, which makes this effortless for the user.

### What settings are you currently utilizing?

- [ ] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

1. Adjust the resources on any LXC container, so they deviate from the defaults.
2. Migrate the update scripts to the new community-scripts repo:
   `sed -i 's/tteck\/Proxmox/community-scripts\/ProxmoxVE/g' /usr/bin/update`
3. run `update`

**Comment by MickLesk** [comment]
Under-provisioning LXC containers is generally not a recommended practice. Containers only use the resources they actually need, regardless of what is allocated to them. For example, even if you assign 64 GB of RAM, a container requiring only 250 MB will only use that amount. Setting resource limits too low can lead to avoidable issues, particularly during resource-intensive tasks like build or update processes.

We introduced these checks to ensure stability and avoid scenarios where builds fail or installations break due to insufficient resources. This was a frequent issue in the past and caused significant frustration for users. While the old approach of temporarily over-provisioning resources might have worked in some cases, it also introduced its own challenges, especially for users who were unaware of these requirements.

The current method ensures that containers meet the minimum resource requirements upfront, providing a more reliable experience overall. If you prefer to maintain custom resource limits, you could consider temporarily increasing resources before running updates and then reverting them afterward. However, consistently meeting the minimum requirements for updates will likely save you time and effort in the long run.

**Comment by dsiebel** [comment]
That is all true and valid and I totally understand the reason why it was done.
I too was one of the users who was having issues with a container once that had insufficient resources to run a `go build` during updates.

Another reason why setting different resource limits, specifically memory, is to help with  garbage collection. While it is true that containers will only consume the resources they need, many (if not all) garbage collected languages actually obey cgroup limits and it has a direct impact on garbage collection and the consumed resources. Hence, running at lower resources limits can help reduce the amount of resources a container _thinks_ it needs.

I am running 40 LXC containers on my Proxmox VE. Having to temporarily update the resource settings to run an update turns a simple, automatable task into a full day of work (see steps involved above).

So, yeah, I basically wanted to gauge the interest in changing the current approach.
One could think about still allowing updates if the container's resource "requirements" aren't met, maybe with a simple `y/n` prompt.

**Comment by MickLesk** [comment]
The problem is, if I add the Y/N question, and we update e.g. an intensive script like Vaultwarden or others, the user has only 4GB RAM and during the update process the installer flies away, so we are only bugfixing. If it is still possible at all, because the process has deleted the folder beforehand. In other words, we are talking about potentially major data loss, which will probably come back to us last.

One idea would have been that you can have a 10-25% deviation from the recommended resources, but even then, we can't ensure that everything is running -> so we get bug reports again.

The right way would rather be to size the LXC's properly, e.g. if you say LXC “Test” has 2 cores and 2 GB RAM according to our specification, but only needs 786MB RAM even when updating, you could scale it down.

**Comment by dsiebel** [comment]
I don't think that is something that can be safely done either.
Memory and CPU consumption highly depends on the usage. I might, for example, have a Photoprism LXC that requires 8 GiB of RAM, 2 CPU and 2TB of Disk, for other users that might look completely different.

Would displaying the warning (no prompt) but still proceeding with the update be an option, to avoid having to deal with bug reports?
Maybe differentiating between scripts that run builds and scripts that don't?

**Comment by dsiebel** [comment]
> The problem is, if I add the Y/N question, and we update e.g. an intensive script like Vaultwarden or others, the user has only 4GB RAM and during the update process the installer flies away, so we are only bugfixing. If it is still possible at all, because the process has deleted the folder beforehand. In other words, we are talking about potentially major data loss, which will probably come back to us last.

Would displaying the warning (no prompt) but still proceeding with the update be an option, to avoid having to deal with bug reports?
Maybe differentiating between scripts that run builds and scripts that don't?

> 
> One idea would have been that you can have a 10-25% deviation from the recommended resources, but even then, we can't ensure that everything is running -> so we get bug reports again.

Yeah, I don't think that 10-25% are going to cut it.
In most cases I could reduce the resource by 50% or less.

> The right way would rather be to size the LXC's properly, e.g. if you say LXC “Test” has 2 cores and 2 GB RAM according to our specification, but only needs 786MB RAM even when updating, you could scale it down.

That is kind-of the problem.
If I scale the container down but the specs are set to higher values, it won't let me update.
Or am I misunderstanding your point here?

**Comment by havardthom** [comment]
Adding a data loss warning and requiring a full `yes` in a prompt like this might be acceptable @MickLesk ?

```
  if [[ "$current_ram" -lt "$var_ram" ]] || [[ "$current_cpu" -lt "$var_cpu" ]]; then
    echo -e "\n⚠️${HOLD} ${GN}Required: ${var_cpu} CPU, ${var_ram}MB RAM ${CL}| ${RD}Current: ${current_cpu} CPU, ${current_ram}MB RAM${CL}"
    echo -e "${YWB}Please ensure that the ${APP} LXC is configured with at least ${var_cpu} vCPU and ${var_ram} MB RAM for the build process.${CL}\n"
    read -r -p "⚠️ May cause data loss! ⚠️ Continue update with under-provisioned LXC? <yes/No>  " prompt  
    # Check if the input is 'yes', otherwise exit with status 1
    if [[ ! ${prompt,,} =~ ^(yes)$ ]]; then
      echo -e "❌${HOLD} ${YWB}Exiting based on user input.${CL}"
      exit 1
    fi
  else
    echo -e ""
  fi
```

**Comment by dsiebel** [comment]
I can also imagine a rollback mechanism, that would not necessarily incur data loss, by having the old release next to the new one and switching symlinks on them.
It's a pattern I've seen quite often in real world projects.
Not sure if that's feasible for all the scripts, since I don't know all of them (yet). But it's definitely something i'd be willing to give a try, when I find the time.

**Comment by MickLesk** [comment]
Do an Example with 2-3 CT.sh and then we take a look.

**Comment by dsiebel** [comment]
I think I will look at these for the implementation:

- `zigbee2mqtt` - elaborate `git clone` update procedure
- `zoraxy` - Simple GitHub release install and I contributed to it before
- `uptimekuma` - because it was the first one that failed on me

If you have other suggestions which ones to look at, please throw them my way.
Will there still be an implementation of @havardthom 's suggestion in the meantime?

**Comment by MickLesk** [comment]
Yes, you are right, LXC resources can be adjusted as desired during active operation. 

This is not possible in the update script because we are not in the Proxmox main node. In other words, you cannot manipulate the RAM and CPU values via this location, this is only possible from the main node.
This is the reason why the install scripts once contained the following “Set resources to normal”, because this was executed via the Proxmox node and was therefore technically possible.

To realize that, all >220 scripts would have to be completely rebuilt, a completely new logic would have to be created. That's not going to happen. Also from a security point of view.

**Comment by MickLesk** [comment]
Closed for now, is included in my PR.

**Comment by burgerga** [comment]
Hi @MickLesk which PR is this? (just curious :) )

And @dsiebel it would still be nice to explore the update/backup symlink logic, maybe we can start a discussion for that?

There are several scripts where in an update the `/opt/$APP` directory is removed, and then a clean install is done. If this fails, there is no way to go back, because a clean install from scratch will also fail.

**Comment by MickLesk** [comment]
not pushed yet, i think tomorrow or today evening (GMT)

**Comment by dsiebel** [comment]
> it would still be nice to explore the update/backup symlink logic, maybe we can start a discussion for that?

@burgerga sure, feel free to start one and mention me for tracking.
Sadly, I haven't found the time to dig into it, yet.
